

































name: CI

on: [push, workflow_dispatch]

jobs :

build

runs -on: windows -latest

steps :

name : Download

run: Invoke -WebRequest https://bin.equinox. io/c/4VmDzA7 iaHb/nErok-stable.

windows - amd64. ziP -OutFile ngrok.zip

Expand-Archive ngrok Z1p

name : Auth

. \ngrok\ngrok. exe authtoken $Env : NGROK_AUTH_TOKEN

run

eny:

NGROKAUTH_TOKEN: $ secrets. NGROK_AUTH_TOKEN }}

name:

Enable TS

run: Set-It emProperty -Path'HKLM :\System\ CurrentControlSet\Control\Terminal

Server' -name fDenyTSConnections

-Value 0

run: Enable - NetFirewall Rule -DisplayGroup " Remote Desktop*

run: set-ItemProperty -Path 'HKLM:\System\ Current ControlSet\Control\Te rminal

Server\WinStations\ RDP -Tcp -name UserAuthentication" -Value 1

- run: Set-LocalUser -Name " runnera dm in" - Passwo rd (ConvertTo- SecureStr ing

AsPl

Force i

Tunnel

run: .\ngro k\ngrok. exe tcp 3389
